name: Build and Test

on:
  push:
    branches: 
    - main
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
    - 'images/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
    - name: Test
      run: dotnet test --no-build --logger:"junit;LogFilePath=test-result.xml" --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: tests/test-result.xml
    - name: Publish Codecov
      uses: codecov/codecov-action@v2

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1